version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    depends_on:
      - creditScoringService

  client:
    build: ./client
    ports:
      - "8081:8081"
    depends_on:
      - backend

  creditScoringService:
    build: ./creditScoringService
    ports:
      - "8000:8000"
