# version: "3.8"

# services:
#   backend:
#     build: ./backend
#     ports:
#       - "5001:5001"
#     depends_on:
#       - creditScoringService

#   client:
#     build: ./client
#     ports:
#       - "8081:8081"
#     depends_on:
#       - backend

#   creditScoringService:
#     build: ./creditScoringService
#     ports:
#       - "8000:8000"



version: "3.8"

services:
  backend:
    container_name: backend-container
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    depends_on:
      - credit-scoring-service
    networks:
      - sharetrack-network

  client:
    container_name: client-container
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - backend
    networks:
      - sharetrack-network

  credit-scoring-service:
    container_name: credit-scoring-container
    build:
      context: ./creditScoringService
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - sharetrack-network

networks:
  sharetrack-network:
    driver: bridge
