# version: "3.8"

# services:
#   backend:
#     container_name: backend-container
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     ports:
#       - "5001:5001"
#     env_file:
#       - ./backend/.env
#     depends_on:
#       - credit-scoring-service
#     networks:
#       - sharetrack-network

#   client:
#     container_name: client-container
#     build:
#       context: ./client
#       dockerfile: Dockerfile
#     ports:
#       - "8081:8081"
#     depends_on:
#       - backend
#     networks:
#       - sharetrack-network

#   credit-scoring-service:
#     container_name: credit-scoring-container
#     build:
#       context: ./creditScoringService
#       dockerfile: Dockerfile
#     ports:
#       - "8000:8000"
#     networks:
#       - sharetrack-network

# networks:
#   sharetrack-network:
#     driver: bridge

version: "3.8"

services:
  backend:
    container_name: backend-container
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    depends_on:
      - credit-scoring-service
    networks:
      - sharetrack-network

  client:
    container_name: client-container
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - backend
    networks:
      - sharetrack-network

  credit-scoring-service:
    container_name: credit-scoring-container
    build:
      context: ./creditScoringService
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - sharetrack-network

  admin-panel:
    container_name: admin-panel-container
    build:
      context: ./admin-panel
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./admin-panel/.env
    depends_on:
      - backend
    networks:
      - sharetrack-network

networks:
  sharetrack-network:
    driver: bridge
